version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mmmt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mmmt-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy --schema=./apps/api/prisma/schema.prisma && node apps/api/main.js"

volumes:
  mysql_data:
